on:
  push:
    branches:
    - master
  pull_request:

name: Build
permissions:
  contents: read
jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run CI
      run: |
        make ci
      env:
        GH_TAG: ${{ github.ref_name }}
        REPO: ghcr.io/${{ github.repository }}
