on:
  push:
    tags:
    - "v*"

env:
  GH_TOKEN: ${{ github.token }}

name: Release
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  release-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Build
      run: |
        make default
      env:
        GH_TAG: ${{ github.ref_name }}
        REPO: ghcr.io/${{ github.repository }}

    - name: Upload bin artifacts
      uses: actions/upload-artifact@v4
      with:
        name: migration-agent
        path: bin/*
        if-no-files-found: error
        retention-days: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        file: package/Dockerfile
        platforms: linux/amd64
